site:
  name: Guslan Putra
  site: 'https://guslan.com'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: Guslan Putra
    template: '%s — Guslan Putra'
  description: "Konsultan Akuntansi & Pajak spesialis industri F&B di Bali dan seluruh Indonesia."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Guslan Putra
    type: website
    
i18n:
  language: id
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

ui:
  theme: system

analytics:
  vendors:
    googleAnalytics:
      id: ~